// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using IntSchool.Sharp.Core.Models;
//
//    var disableParentAccountRequestModel = ParentAccountIdRequestModel.FromJson(jsonString);

namespace IntSchool.Sharp.Core.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ParentAccountIdRequestModel
    {
        [JsonProperty("parentId")]
        public long ParentId { get; set; }
    }

    public partial class ParentAccountIdRequestModel
    {
        public static ParentAccountIdRequestModel FromJson(string json) => JsonConvert.DeserializeObject<ParentAccountIdRequestModel>(json, ConverterParentAccountIdRequestModel.Settings);
    }

    public static class SerializeParentAccountIdRequestModel
    {
        public static string ToJson(this ParentAccountIdRequestModel self) => JsonConvert.SerializeObject(self, ConverterParentAccountIdRequestModel.Settings);
    }

    internal static class ConverterParentAccountIdRequestModel
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
