// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using IntSchool.Sharp.Models;
//
//    var getMarkListResponseModel = GetMarkListResponseModel.FromJson(jsonString);

namespace IntSchool.Sharp.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class GetMarkListResponseModel
    {
        [JsonProperty("pageSize")]
        public long PageSize { get; set; }

        [JsonProperty("pageCurrent")]
        public long PageCurrent { get; set; }

        [JsonProperty("totalItem")]
        public long TotalItem { get; set; }

        [JsonProperty("items")]
        public List<GetMarkListItem> Items { get; set; }
    }

    public partial class GetMarkListItem
    {
        [JsonProperty("entityId")]
        public long EntityId { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("endDate")]
        public long EndDate { get; set; }

        [JsonProperty("score")]
        public double? Score { get; set; }

        [JsonProperty("topScore")]
        public long TopScore { get; set; }

        [JsonProperty("creatorName")]
        public string CreatorName { get; set; }

        [JsonProperty("displayName")]
        public string DisplayName { get; set; }

        [JsonProperty("startDate")]
        public long StartDate { get; set; }

        [JsonProperty("status")]
        public bool Status { get; set; }

        [JsonProperty("isRead")]
        public bool IsRead { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("online")]
        public bool Online { get; set; }
    }

    public partial class GetMarkListResponseModel
    {
        public static GetMarkListResponseModel FromJson(string json) => JsonConvert.DeserializeObject<GetMarkListResponseModel>(json, IntSchool.Sharp.Models.ConverterGetMarkListResponseModel.Settings);
    }

    public static class SerializeGetMarkListResponseModel
    {
        public static string ToJson(this GetMarkListResponseModel self) => JsonConvert.SerializeObject(self, IntSchool.Sharp.Models.ConverterGetMarkListResponseModel.Settings);
    }

    internal static class ConverterGetMarkListResponseModel
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
