// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using IntSchool.Sharp.Models;
//
//    var getStudentCurriculumResponseModel = GetStudentCurriculumResponseModel.FromJson(jsonString);

namespace IntSchool.Sharp.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class GetStudentCurriculumResponseModel
    {
        [JsonProperty("classArranges")]
        public Dictionary<string, Dictionary<string, ClassArrange>> ClassArranges { get; set; }

        [JsonProperty("classPeriods")]
        public List<ClassPeriod> ClassPeriods { get; set; }

        [JsonProperty("dayOfArranged")]
        public List<object> DayOfArranged { get; set; }
    }

    public partial class ClassArrange
    {
        [JsonProperty("classArrangeId")]
        public long ClassArrangeId { get; set; }

        [JsonProperty("classRoomId")]
        public ClassRoomId ClassRoomId { get; set; }

        [JsonProperty("courseId")]
        public CourseId CourseId { get; set; }

        [JsonProperty("targetSections")]
        public List<TargetSection> TargetSections { get; set; }

        [JsonProperty("startTime")]
        public long StartTime { get; set; }

        [JsonProperty("endTime")]
        public long EndTime { get; set; }

        [JsonProperty("week")]
        public long? Week { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("originDayOfWeek")]
        public object OriginDayOfWeek { get; set; }

        [JsonProperty("teachers")]
        public List<ClassArrangeTeacher> Teachers { get; set; }
    }

    public partial class ClassRoomId
    {
        [JsonProperty("seqNum")]
        public object SeqNum { get; set; }

        [JsonProperty("classRoomId")]
        public long? ClassRoomIdClassRoomId { get; set; }

        [JsonProperty("code")]
        public string Code { get; set; }
    }

    public partial class CourseId
    {
        [JsonProperty("courseId")]
        public long? CourseIdCourseId { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("subject")]
        public Subject Subject { get; set; }

        [JsonProperty("students")]
        public List<Student> Students { get; set; }

        [JsonProperty("teacher")]
        public List<CourseIdTeacher> Teacher { get; set; }
    }

    public partial class Student
    {
        [JsonProperty("studentId")]
        public long StudentId { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    public partial class Subject
    {
        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("subjectId")]
        public long SubjectId { get; set; }

        [JsonProperty("color")]
        public string Color { get; set; }
    }

    public partial class CourseIdTeacher
    {
        [JsonProperty("teacherId")]
        public long TeacherId { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("enName")]
        public string EnName { get; set; }

        [JsonProperty("displayName")]
        public string DisplayName { get; set; }

        [JsonProperty("avatarUrl")]
        public string AvatarUrl { get; set; }

        [JsonProperty("classTeacher")]
        public bool ClassTeacher { get; set; }

        [JsonProperty("courseTeacher")]
        public bool CourseTeacher { get; set; }

        [JsonProperty("houseTeacher")]
        public bool HouseTeacher { get; set; }

        [JsonProperty("sectionTeacher")]
        public bool SectionTeacher { get; set; }
    }

    public partial class TargetSection
    {
        [JsonProperty("seqNum")]
        public object SeqNum { get; set; }

        [JsonProperty("campusName")]
        public string CampusName { get; set; }

        [JsonProperty("sectionName")]
        public string SectionName { get; set; }

        [JsonProperty("sectionCampusId")]
        public long SectionCampusId { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("teachers")]
        public List<object> Teachers { get; set; }
    }

    public partial class ClassArrangeTeacher
    {
        [JsonProperty("teacherId")]
        public long TeacherId { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("isSubstitute")]
        public bool IsSubstitute { get; set; }
    }

    public partial class ClassPeriod
    {
        [JsonProperty("classPeriodId")]
        public long ClassPeriodId { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("start")]
        public long Start { get; set; }

        [JsonProperty("end")]
        public long End { get; set; }

        [JsonProperty("sevenFive")]
        public bool SevenFive { get; set; }

        [JsonProperty("isFullPeriodArranged")]
        public bool IsFullPeriodArranged { get; set; }
    }

    public partial class GetStudentCurriculumResponseModel
    {
        public static GetStudentCurriculumResponseModel FromJson(string json) => JsonConvert.DeserializeObject<GetStudentCurriculumResponseModel>(json, IntSchool.Sharp.Models.ConverterGetStudentCurriculumResponseModel.Settings);
    }

    public static class SerializeGetStudentCurriculumResponseModel
    {
        public static string ToJson(this GetStudentCurriculumResponseModel self) => JsonConvert.SerializeObject(self, IntSchool.Sharp.Models.ConverterGetStudentCurriculumResponseModel.Settings);
    }

    internal static class ConverterGetStudentCurriculumResponseModel
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
