// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using IntSchool.Sharp.Models;
//
//    var sendSmsResponseModel = SendSmsResponseModel.FromJson(jsonString);

namespace IntSchool.Sharp.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class SendSmsResponseModel
    {
        [JsonProperty("success")]
        public bool Success { get; set; }

        [JsonProperty("resCode")]
        public object ResCode { get; set; }

        [JsonProperty("resMsg")]
        public string ResMsg { get; set; }
    }

    public partial class SendSmsResponseModel
    {
        public static SendSmsResponseModel FromJson(string json) => JsonConvert.DeserializeObject<SendSmsResponseModel>(json, IntSchool.Sharp.Models.ConverterSendSmsResponseModel.Settings);
    }

    public static class SerializeSendSmsResponseModel
    {
        public static string ToJson(this SendSmsResponseModel self) => JsonConvert.SerializeObject(self, IntSchool.Sharp.Models.ConverterSendSmsResponseModel.Settings);
    }

    internal static class ConverterSendSmsResponseModel
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}