// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using IntSchool.Sharp.Models;
//
//    var loginByMailRequestModel = LoginByPasswordRequestModel.FromJson(jsonString);

namespace IntSchool.Sharp.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class LoginByPasswordRequestModel
    {
        [JsonProperty("account")]
        public string Account { get; set; }

        [JsonProperty("password")]
        public string Password { get; set; }
    }

    public partial class LoginByPasswordRequestModel
    {
        public static LoginByPasswordRequestModel FromJson(string json) => JsonConvert.DeserializeObject<LoginByPasswordRequestModel>(json, IntSchool.Sharp.Models.ConverterLoginByMailRequestModel.Settings);
    }

    public static class SerializeLoginByMailRequestModel
    {
        public static string ToJson(this LoginByPasswordRequestModel self) => JsonConvert.SerializeObject(self, IntSchool.Sharp.Models.ConverterLoginByMailRequestModel.Settings);
    }

    internal static class ConverterLoginByMailRequestModel
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
