// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using IntSchool.Sharp.Core.Models;
//
//    var updateParentAccountRequestModel = UpdateParentAccountRequestModel.FromJson(jsonString);

namespace IntSchool.Sharp.Core.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class UpdateParentAccountRequestModel
    {
        [JsonProperty("parentId")]
        public long ParentId { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("enName")]
        public string EnName { get; set; }

        [JsonProperty("mobile")]
        public string Mobile { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("countryId")]
        public long CountryId { get; set; }

        [JsonProperty("countryName")]
        public string CountryName { get; set; }

        [JsonProperty("workUnit")]
        public string WorkUnit { get; set; }

        [JsonProperty("position")]
        public string Position { get; set; }

        [JsonProperty("graduatedFrom")]
        public string GraduatedFrom { get; set; }

        [JsonProperty("wxid")]
        public string Wxid { get; set; }

        [JsonProperty("highestQualification")]
        public object HighestQualification { get; set; }

        [JsonProperty("highestQualificationName")]
        public string HighestQualificationName { get; set; }

        [JsonProperty("highestQualificationEnName")]
        public string HighestQualificationEnName { get; set; }

        [JsonProperty("students")]
        public List<UpdateParentAccountRequestModelStudent> Students { get; set; }
    }

    public partial class UpdateParentAccountRequestModelStudent
    {
        [JsonProperty("studentId")]
        public long StudentId { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("studentNum")]
        public string StudentNum { get; set; }

        [JsonProperty("relationship")]
        public string Relationship { get; set; }

        [JsonProperty("sectionName")]
        public string SectionName { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("canDelete")]
        public bool CanDelete { get; set; }
    }

    public partial class UpdateParentAccountRequestModel
    {
        public static UpdateParentAccountRequestModel FromJson(string json) => JsonConvert.DeserializeObject<UpdateParentAccountRequestModel>(json, ConverterUpdateParentAccountRequestModel.Settings);
    }

    public static class SerializeUpdateParentAccountRequestModel
    {
        public static string ToJson(this UpdateParentAccountRequestModel self) => JsonConvert.SerializeObject(self, ConverterUpdateParentAccountRequestModel.Settings);
    }

    internal static class ConverterUpdateParentAccountRequestModel
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
