// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using IntSchool.Sharp.Models;
//
//    var loginByVerifySmsRequestModel = LoginByVerifySmsRequestModel.FromJson(jsonString);

namespace IntSchool.Sharp.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class LoginByVerifySmsRequestModel(string areaCode, string mobile, string verifyCode)
    {
        [JsonProperty("account")] public string Account { get; set; } = mobile;

        [JsonProperty("vcode")] public string Vcode { get; set; } = verifyCode;

        [JsonProperty("areaCode")] public string AreaCode { get; set; } = areaCode;
    }

    public partial class LoginByVerifySmsRequestModel
    {
        public static LoginByVerifySmsRequestModel FromJson(string json) => JsonConvert.DeserializeObject<LoginByVerifySmsRequestModel>(json, IntSchool.Sharp.Models.ConverterLoginByVerifySmsRequestModel.Settings);
    }

    public static class SerializeLoginByVerifySmsRequestModel
    {
        public static string ToJson(this LoginByVerifySmsRequestModel self) => JsonConvert.SerializeObject(self, IntSchool.Sharp.Models.ConverterLoginByVerifySmsRequestModel.Settings);
    }

    internal static class ConverterLoginByVerifySmsRequestModel
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
