// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using IntSchool.Sharp.Models;
//
//    var postLeaveRequestRequestModel = PostLeaveRequestRequestModel.FromJson(jsonString);

namespace IntSchool.Sharp.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class PostLeaveRequestRequestModel
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("startTime")]
        public long StartTime { get; set; }

        [JsonProperty("endTime")]
        public long EndTime { get; set; }

        [JsonProperty("reason")]
        public string Reason { get; set; }

        [JsonProperty("studentId")]
        public string StudentId { get; set; }

        [JsonProperty("resourceIds")] public List<object> ResourceIds { get; set; } = new List<object>();

        [JsonProperty("reasonId")]
        public long ReasonId { get; set; }
    }

    public partial class PostLeaveRequestRequestModel
    {
        public static PostLeaveRequestRequestModel FromJson(string json) => JsonConvert.DeserializeObject<PostLeaveRequestRequestModel>(json, IntSchool.Sharp.Models.ConverterPostLeaveRequestRequestModel.Settings);
    }

    public static class SerializePostLeaveRequestRequestModel
    {
        public static string ToJson(this PostLeaveRequestRequestModel self) => JsonConvert.SerializeObject(self, IntSchool.Sharp.Models.ConverterPostLeaveRequestRequestModel.Settings);
    }

    internal static class ConverterPostLeaveRequestRequestModel
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
